### PR TITLE
Complaint Management Section - confirmation screen

### PR DESCRIPTION
**Pull request by sr2005roy**
feat: Added Complaint Management Section - confirmation screen
style: Styled the Confirmation Screen. 
fixes: #4

### CODE REVIEW

**Comment by sr2005roy** [comment]
@g-kabra @TsarPrince
Can you please help me sort this issue

**Comment by sr2005roy** [comment]
image
image
image

**Comment by sr2005roy** [comment]
iys int the complaint router (http://localhost:5173/complaint)

**Comment by TsarPrince** [comment]
> @g-kabra @TsarPrince Can you please help me sort this issue

Here are the logs from vercel itself. I will leave it up to you to debug the issue. Also, vercel builds a production build of the app before deploying, so you can also generate the following logs at your level by running `npm run build` or `yarn build`. Let us know if you still need some help.

```
RollupError: Could not resolve "./pages/complaint/complaint.page.jsx" from "src/app.jsx"
--
20:01:38.413 | at error (file:///vercel/path0/node_modules/rollup/dist/es/shared/node-entry.js:2128:30)
20:01:38.413 | at ModuleLoader.handleInvalidResolvedId (file:///vercel/path0/node_modules/rollup/dist/es/shared/node-entry.js:23782:24)
20:01:38.413 | at file:///vercel/path0/node_modules/rollup/dist/es/shared/node-entry.js:23744:26
20:01:38.447 | error Command failed with exit code 1.
20:01:38.447 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
20:01:38.465 | Error: Command "yarn run build" exited with 1
20:01:38.860 | Deployment completed
20:01:38.825 | BUILD_UTILS_SPAWN_1: Command "yarn run build" exited with 1
```

**Pull request closed without merging**
